# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'   # or specify: '3.24.3'

      # 3️⃣ Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Analyze code (optional)
      - name: Analyze project
        run: flutter analyze

      # 5️⃣ Build APK (debug/release)
      - name: Build release APK
        run: flutter build apk --release

      # 6️⃣ Upload the built APK to GitHub artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
