# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual trigger from the Actions tab

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter (FIXED: use explicit version or channel)
      # Option A: Use a fixed Flutter version (recommended for stability)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      # Option B: (Alternative) use latest stable channel instead
      # - name: Setup Flutter
      #   uses: subosito/flutter-action@v2
      #   with:
      #     channel: 'stable'

      # 3️⃣ Get dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ Analyze code (optional)
      - name: Analyze project
        run: flutter analyze || true

      # 5️⃣ Build APK (release version)
      - name: Build release APK
        run: flutter build apk --release

      # 6️⃣ Upload the built APK to GitHub artifacts
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
